"""rename the name column of the users table

Revision ID: 41544070fec8
Revises: a4647ff38e75
Create Date: 2023-08-17 08:48:01.865518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41544070fec8'
down_revision: Union[str, None] = 'a4647ff38e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('name', new_column_name='username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('username', new_column_name='name')
    # ### end Alembic commands ###
